table_columns_type = {
    'aditivos_contratos': [
        ('cod_unidade','int'),
        ('ente','string'),
        ('unidade', 'string'),
        ('numero_contrato', 'string'),
        ('ano', 'int'),
        ('numero_aditivo', 'string'),
        ('objeto_aditivo', 'string'),
        ('fundamentacao_legal_aditivo', 'string'),
        ('data_assinatura_aditivo', 'timestamp'),
        ('data_inicio_aditivo', 'timestamp'),
        ('data_termino_aditivo', 'timestamp'),
        ('data_publicacao_aditivo', 'timestamp'),
        ('veiculo_publicacao', 'string'),
        ('valor_aditivo', 'decimal'),
    ],
    'alteracao_orcamentaria': [
        ('codigo_unidade','int'),
        ('ente','string'),
        ('unidade','string'),
        ('ano','int'),
        ('codigo_dotacao','string'),
        ('codigo_funcao','int'),
        ('funcao','string'),
        ('codigo_subfuncao','int'),
        ('subfuncao','string'),
        ('codigo_orgao','int'),
        ('orgao','string'),
        ('codigo_unidadeorcamentaria','int'),
        ('unidadeorcamentaria','string'),
        ('codigo_programa','int'),
        ('programa','string'),
        ('codigo_fonterecurso_gestor','int'),
        ('fonterecurso_gestor','string'),
        ('codigo_fonterecurso_tce','int'),
        ('fonterecurso_tce','string'),
        ('codigo_projeto_atividade','int'),
        ('codigo_tipo_projetoatividade','int'),
        ('tipo_projetoatividade','string'),
        ('projeto_atividade','string'),
        ('codigo_elemento_gestor','int'),
        ('elemento_gestor','string'),
        ('codigo_elemento_tce','int'),
        ('elemento_tce','string'),
        ('data_alteracao','timestamp'),
        ('lei_autorizativa','string'),
        ('decreto','string'),
        ('data_publicacao_decreto','timestamp'),
        ('codigo_alteracao','int'),
        ('tipo_alteracao','string'),
        ('codigo_tipo_fundamento','int'),
        ('tipo_fundamento','string'),
        ('data_fundamento','timestamp'),
        ('valor_alteracao','decimal')
    ],
    'alteracos_receita': [
        ('codigounidade','int'),
        ('ente','string'),
        ('unidade','string'),
        ('ano','int'),
        ('competencia','int'),
        ('codigoitemgestor','bigint'),
        ('descricaoitemgestor','string'),
        ('codigoitemtce','bigint'),
        ('descricaoitemtce','string'),
        ('tipoatualizacao','string'),
        ('valorreceita','decimal')
    ],
    'contratos': [
        ('cod_unidade','int'),
        ('ente','string'),
        ('unidade','string'),
        ('numero_contrato','string'),
        ('ano','int'),
        ('numero_processolicitatorio','string'),
        ('tp_pessoacontratado','int'),
        ('tipo_pessoa','string'),
        ('cod_moeda','int'),
        ('moeda','string'),
        ('objetivocontrato','string'),
        ('cpf_cnpj','string'),
        ('contratado','string'),
        ('data_assinaturacontrato','timestamp'),
        ('veiculo_publicacao','string'),
        ('data_publicacao','timestamp'),
        ('valor_contrato','decimal'),
        ('data_inicioexecucao','timestamp'),
        ('data_terminoexecucao','timestamp'),
        ('numero_processodispensa','string'),
        ('codigo_tipocontrato','int'),
        ('tipocontrato','string')
    ],
    'dados_covid_estadual': [
        ('_c0','int'),
        ('periodo','string'),
        ('numerointerno','int'),
        ('ente','string'),
        ('unidadegestora','string'),
        ('processoadministrativo','string'),
        ('protocolointegracao','string'),
        ('valor','double'),
        ('dataato','timestamp'),
        ('cpfordenador','string'),
        ('nomeordenador','string'),
        ('tipopessoa','string'),
        ('cpfcnpj','string'),
        ('nomerazaosocial','string'),
        ('objeto','string'),
        ('numeroitem','int'),
        ('descricao','string'),
        ('precounitario','double'),
        ('quantidade','double'),
        ('unidademedida','string'),
        ('datapublicacao','timestamp'),
        ('veiculocomunicacao','string'),
        ('fundamentacaolegal','string'),
        ('tipologia','string'),
        ('possuicontrato','string'),
        ('motivoausenciacontrato','string'),
        ('justificativaausenciacontrato','string'),
        ('numerocontrato','string'),
        ('processoadministrativocontrato','string'),
        ('dataassinaturacontrato','timestamp'),
        ('datainiciocontrato','timestamp'),
        ('dataterminocontrato','timestamp'),
        ('valorcontrato','double'),
        ('datapublicacaocontrato','timestamp'),
        ('veiculocomunicacaocontrato','string'),
        ('codigosiafe','string'),
        ('situacao','string'),
        ('datasituacao','timestamp'),
        ('dataultimaatualizacao','timestamp')
    ],
    'dados_covid_municipal': [
        ('_c0','int'),
        ('periodo','string'),
        ('numerointerno','int'),
        ('ente','string'),
        ('unidadegestora','string'),
        ('processoadministrativo','string'),
        ('protocolointegracao','string'),
        ('valor','double'),
        ('dataato','timestamp'),
        ('cpfordenador','string'),
        ('nomeordenador','string'),
        ('tipopessoa','string'),
        ('cpfcnpj','string'),
        ('nomerazaosocial','string'),
        ('objeto','string'),
        ('numeroitem','int'),
        ('descricao','string'),
        ('precounitario','double'),
        ('quantidade','double'),
        ('unidademedida','string'),
        ('datapublicacao','timestamp'),
        ('veiculocomunicacao','string'),
        ('fundamentacaolegal','string'),
        ('tipologia','string'),
        ('possuicontrato','string'),
        ('motivoausenciacontrato','string'),
        ('justificativaausenciacontrato','string'),
        ('numerocontrato','string'),
        ('processoadministrativocontrato','string'),
        ('dataassinaturacontrato','timestamp'),
        ('datainiciocontrato','timestamp'),
        ('dataterminocontrato','timestamp'),
        ('valorcontrato','double'),
        ('datapublicacaocontrato','timestamp'),
        ('veiculocomunicacaocontrato','string'),
        ('codigosiafe','string'),
        ('situacao','string'),
        ('datasituacao','timestamp'),
        ('dataultimaatualizacao','timestamp')
    ],
    'dotacoes': [
        ('codigo_unidade','int'),
        ('ente','string'),
        ('unidade','string'),
        ('ano','int'),
        ('codigo_dotacao','string'),
        ('codigo_funcao','int'),
        ('funcao','string'),
        ('codigo_subfuncao','int'),
        ('subfuncao','string'),
        ('codigo_orgao','int'),
        ('orgao','string'),
        ('codigo_unidadeorcamentaria','int'),
        ('unidadeorcamentaria','string'),
        ('codigo_programa','int'),
        ('programa','string'),
        ('codigo_fonterecurso_gestor','int'),
        ('fonterecurso_gestor','string'),
        ('codigo_fonterecurso_tce','int'),
        ('fonterecurso_tce','string'),
        ('codigo_projeto_atividade','int'),
        ('projeto_atividade','string'),
        ('codigo_elemento_gestor','int'),
        ('elemento_gestor','string'),
        ('codigo_elemento_tce','int'),
        ('elemento_tce','string'),
        ('valor_dotacao','decimal')
    ],
    'receita_orcada': [
        ('codigounidade','int'),
        ('ente','string'),
        ('unidade','string'),
        ('ano','int'),
        ('codigoitemgestor','bigint'),
        ('descricaoitemgestor','string'),
        ('codigoitemtce','bigint'),
        ('descricaoitemtce','string'),
        ('valorreceita','decimal')
    ],
    'receitas_arrecadadas': [
        ('codigo_unidade','int'),
        ('ente','string'),
        ('unidade','string'),
        ('ano','int'),
        ('competencia','timestamp'),
        ('codigo_item_tce','bigint'),
        ('descricao_item_tce','string'),
        ('item_gestor','bigint'),
        ('descricao_gestor','string'),
        ('tipo_receita','string'),
        ('valor_receita','decimal')
    ]
}