CREATE TABLE detran_multa_opv(  uuid string,   autoinfra string,   datainfra timestamp,   descinfra string,   cpfcnpj string,   proprietario string,   placa string,   label string) STORED AS PARQUET;
CREATE TABLE detran_veiculo_opv(  uuid string,   fabric int,   modelo int,   chassi string,   descricao_cor string,   cpfcgc string,   marca_modelo string,   placa string,   renavam string,   proprietario string,   label string) STORED AS PARQUET;
CREATE TABLE documento_opv(  uuid string,   cdorgao int,   cldc_ds_hierarquia string,   docu_dk int,   dt_cadastro timestamp,   nr_externo string,   nr_mp string,   label string) STORED AS PARQUET;
CREATE TABLE documento_orgao_ope(  start_node string,   end_node string,   label string,   uuid string) STORED AS PARQUET;
CREATE TABLE documento_personagem_ope(  start_node string,   end_node string,   label string,   uuid string) STORED AS PARQUET;
CREATE TABLE embarcacao_opv(  uuid string,   nome_embarcacao string COMMENT 'from deserializer',   tipo_embarcacao string COMMENT 'from deserializer',   ano_construcao string COMMENT 'from deserializer',   nr_inscricao string COMMENT 'from deserializer',   cpf_cnpj string COMMENT 'from deserializer',   label string) STORED AS PARQUET;
CREATE TABLE empresa_embarcacao_ope(  start_node string,   end_node string,   label string,   uuid string) STORED AS PARQUET;
CREATE TABLE empresa_multa_ope(  start_node string,   end_node string,   label string,   uuid string) STORED AS PARQUET;
CREATE TABLE empresa_veiculo_ope(  start_node string,   end_node string,   label string,   uuid string) STORED AS PARQUET;
CREATE TABLE maternidade_ope(  start_node string,   end_node string,   uuid string,   label string) STORED AS PARQUET;
CREATE TABLE orgao_mprj_ope(  start_node string,   end_node string,   label string,   uuid string) STORED AS PARQUET;
CREATE TABLE orgao_opv(  uuid string,   cd_orgao int,   nm_orgao string,   nm_regiao string,   nm_comarca string,   nm_foro string,   nm_tporgao string,   label string) STORED AS PARQUET;
CREATE TABLE paternidade_ope(  start_node string,   end_node string,   uuid string,   label string) STORED AS PARQUET;
CREATE TABLE personagem_documento_ope(  start_node string,   end_node string,   label string,   uuid string) STORED AS PARQUET;
CREATE TABLE personagem_opv(  uuid string,   pers_dk int,   pers_docu_dk int,   pers_dt_inicio timestamp,   pers_dt_fim timestamp,   label string,   tppe_descricao string,   cpfcnpj string,   pess_nm_pessoa string) STORED AS PARQUET;
CREATE TABLE personagem_pessoa_ope(  start_node string,   end_node string,   label string,   uuid string) STORED AS PARQUET;
CREATE TABLE pessoa_embarcacao_ope(  start_node string,   end_node string,   label string,   uuid string) STORED AS PARQUET;
CREATE TABLE pessoa_fisica_opv(  uuid string,   num_cpf char(11),   data_nascimento timestamp,   nome varchar(100),   nome_mae varchar(60),   ind_sexo char(1),   sigla_uf varchar(2),   num_rg string,   nome_rg string,   nome_pai string,   sensivel int,   label string) STORED AS PARQUET;
CREATE TABLE pessoa_juridica_opv(  uuid string,   nome_fantasia varchar(55),   razao_social varchar(150),   num_cnpj varchar(14),   num_cpf_responsavel varchar(11),   data_abertura_estabelecimento timestamp,   ind_matriz_filial decimal(1,0),   nome_municipio varchar(50),   sigla_uf varchar(2),   label string) STORED AS PARQUET;
CREATE TABLE pessoa_mae_ope(  start_node string,   end_node string,   uuid string,   parentesco string,   label string) STORED AS PARQUET;
CREATE TABLE pessoa_multa_ope(  start_node string,   end_node string,   label string,   uuid string) STORED AS PARQUET;
CREATE TABLE pessoa_pai_ope(  start_node string,   end_node string,   uuid string,   parentesco string,   label string) STORED AS PARQUET;
CREATE TABLE pessoa_personagem_ope(  start_node string,   end_node string,   label string,   uuid string) STORED AS PARQUET;
CREATE TABLE pessoa_veiculo_ope(  start_node string,   end_node string,   label string,   uuid string) STORED AS PARQUET;
CREATE TABLE socio_ope(  label string,   start_node string,   end_node string,   dt_inicio timestamp,   dt_fim timestamp,   tipo_socio varchar(60),   uuid string) STORED AS PARQUET;
CREATE TABLE socio_responsavel_ope(  label string,   start_node string,   end_node string,   uuid string) STORED AS PARQUET;
CREATE TABLE veiculo_multa_ope(  start_node string,   end_node string,   label string,   uuid string) STORED AS PARQUET;
CREATE TABLE vinculo_trabalhista_ope(  uuid string,   label string,   start_node string,   end_node string,   dt_inicio timestamp,   dt_fim timestamp,   vinc_ativo int) STORED AS PARQUET;
