CREATE TABLE entidade_craai(  idcraai int,   nm_orgao string)ROW FORMAT SERDE   'org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe' STORED AS INPUTFORMAT   'org.apache.hadoop.mapred.TextInputFormat' OUTPUTFORMAT   'org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat'LOCATION  'hdfs://mpmapas-ns/user/hive/warehouse/lupa.db/entidade_craai'TBLPROPERTIES (  'COLUMN_STATS_ACCURATE'='true',   'numFiles'='2',   'numRows'='15',   'rawDataSize'='296',   'totalSize'='311',   'transient_lastDdlTime'='1564609733')
CREATE VIEW lp_acervo_atual AS SELECT CAST(CAST(docu_orgi_orga_dk_responsavel AS INT) AS STRING) cdorg, nvl(split_part(cldc_ds_hierarquia, '|', 1), '* SEM CLASSE CADASTRADA *') classe_pai, count(docu_dk) total_documentos FROM exadata.mcpr_documento LEFT OUTER JOIN exadata_aux.mmps_classe_hierarquia ON CAST(CAST(docu_cldc_dk AS INT) AS STRING) = cldc_dk WHERE docu_fsdc_dk = 1 GROUP BY cdorg, classe_pai ORDER BY total_documentos DESC LIMIT 10000000
CREATE VIEW lp_cargos_mp AS SELECT 33 as uf, lp_movimentacao_rh.codigo_municipio as cod_mun,count(DISTINCT lp_movimentacao_rh.cdmatricula) as quant,lp_movimentacao_rh.nmcargo as cargoFROM lupa.lp_movimentacao_rhGROUP BY lp_movimentacao_rh.codigo_municipio, lp_movimentacao_rh.nmcargo
CREATE VIEW lp_craai_outros_orgaos AS SELECT CAST(orlw_regi_dk AS STRING) orlw_regi_dk, orgao.ORGI_CDORGAO, orgao.ORGI_NM_ORGAO, craai.ORLW_REGI_NM_REGIAO, tipoorgao.TPOR_DK, tipoorgao.TPOR_DS_TP_ORGAO, 'ORG' destino FROM exadata.orgi_orgao orgao INNER JOIN exadata.orgi_vw_orgao_local_atual craai ON craai.ORLW_ORGI_CDORGAO = orgao.ORGI_CDORGAO INNER JOIN exadata.orgi_tp_orgao tipoorgao ON tipoorgao.tpor_dk = orgao.ORGI_TPOR_DK WHERE orgi_tpor_dk NOT IN (1, 3, 5) AND ((orgi_dt_fim IS NULL) OR orgi_dt_fim >= now()) ORDER BY orgao.orgi_nm_orgao ASC LIMIT 100000000
CREATE VIEW lp_craai_procuradorias AS SELECT CAST(orlw_regi_dk AS STRING) orlw_regi_dk, orgao.ORGI_CDORGAO, orgao.ORGI_NM_ORGAO, craai.ORLW_REGI_NM_REGIAO, tipoorgao.TPOR_DK, tipoorgao.TPOR_DS_TP_ORGAO, 'PRC' destino FROM exadata.orgi_orgao orgao INNER JOIN exadata.orgi_vw_orgao_local_atual craai ON craai.ORLW_ORGI_CDORGAO = orgao.ORGI_CDORGAO INNER JOIN exadata.orgi_tp_orgao tipoorgao ON tipoorgao.tpor_dk = orgao.ORGI_TPOR_DK WHERE orgi_tpor_dk = 3 AND ((orgi_dt_fim IS NULL) OR orgi_dt_fim >= now()) ORDER BY orgao.orgi_nm_orgao ASC LIMIT 10000
CREATE VIEW lp_craai_promotorias AS SELECT CAST(orlw_regi_dk AS STRING) orlw_regi_dk, orgao.ORGI_CDORGAO, orgao.ORGI_NM_ORGAO, craai.ORLW_REGI_NM_REGIAO, tipoorgao.TPOR_DK, tipoorgao.TPOR_DS_TP_ORGAO, 'PRO' destino FROM exadata.orgi_orgao orgao INNER JOIN exadata.orgi_vw_orgao_local_atual craai ON craai.ORLW_ORGI_CDORGAO = orgao.ORGI_CDORGAO INNER JOIN exadata.orgi_tp_orgao tipoorgao ON tipoorgao.tpor_dk = orgao.ORGI_TPOR_DK WHERE orgi_tpor_dk = 1 AND ((orgi_dt_fim IS NULL) OR orgi_dt_fim >= now()) ORDER BY orgao.orgi_nm_orgao ASC LIMIT 100000000
CREATE VIEW lp_custos_tipo_estado AS SELECT '33' cod_ibge, tipo_de_custo, sum(total) total FROM opengeo.financeiro WHERE EXTRACT(year FROM competencia) >= EXTRACT(year FROM now()) GROUP BY tipo_de_custo ORDER BY total DESC LIMIT 1000000000
CREATE VIEW lp_dados_municipio AS SELECT CAST(prefeituras.cod_municipio AS STRING) cod_municipio, cod_craai, '' nome, concat('Data de Fundação: ', municipio_flag.aniversario, '@', 'Legislação de Criação: ', municipio_flag.criacao, '@', 'Gentílico: ', prefeituras.gentilico) detalhes, flag foto FROM opengeo.lupa_prefeituras prefeituras INNER JOIN opengeo.municipio_flag ON municipio_flag.cod_municipio = prefeituras.cod_municipio
CREATE VIEW lp_governantes AS SELECT CAST(cod_ibge AS STRING) cod_ibge, nome, concat('Mandato: ', CAST(ano_eleicao + 1 AS STRING), '/', CAST(ano_eleicao + 4 AS STRING)) detalhes, base64_foto foto FROM opengeo.lupa_governantes_rj governantes
CREATE VIEW lp_membros_mp AS SELECT 33 as uf,CAST(lp_movimentacao_rh.codigo_municipio as string)  as cod_mun,count(DISTINCT lp_movimentacao_rh.cdmatricula) as quant_membrosFROM lupa.lp_movimentacao_rhWHERE lp_movimentacao_rh.cdcargo IN ('70', '74')GROUP BY lp_movimentacao_rh.codigo_municipio
CREATE VIEW lp_movimentacao_rh AS SELECT rh_f.cdmatricula, rh_f.cdcargo, rh_c.nmcargo, rh_f.cdtipfunc, rh_tf.dstipfunc, year(current_timestamp()) - year(rh_f.dtnasc) idade, rh_f.sexo, org.codigo_municipio, org.municipio FROM exadata.rh_funcionario rh_f INNER JOIN opengeo.lupa_orgaos_mprj org ON CAST(rh_f.cdorgao AS INT) = org.codigo_mgo INNER JOIN exadata.rh_cargos rh_c ON rh_c.cdcargo = rh_f.cdcargo LEFT OUTER JOIN exadata_aux.tipo_funcionario rh_tf ON rh_tf.cdtipfunc = CAST(rh_f.cdtipfunc AS INT)
CREATE VIEW lp_orgao_acervo AS SELECT CAST(cdorgao AS STRING) cdorgao, dt, CAST(entradas - saidas AS INT) acumulo, tipo FROM cluster.painel_acervo WHERE dt > add_months(now(), -8)
CREATE VIEW lp_orgao_financeiro_exercicio_atual AS SELECT codigo_cc, item_de_custo, sum(total) total FROM opengeo.financeiro WHERE EXTRACT(year FROM competencia) = EXTRACT(year FROM now()) GROUP BY codigo_cc, item_de_custo HAVING total > 0 ORDER BY total DESC LIMIT 10000
CREATE VIEW lp_orgaos_auxiliares AS SELECT orgao.orgi_nm_orgao, CAST(orgao.orgi_dk AS STRING) orgao_auxilizar, CAST(auxilia.orau_orgi_dk_auxilia AS STRING) orgao_auxiliado FROM exadata.orgi_auxilia auxilia INNER JOIN exadata.orgi_orgao orgao ON auxilia.orau_orgi_dk = orgao.orgi_dk WHERE orgao.orgi_tpor_dk NOT IN (5)
CREATE VIEW lp_predio_custos_por_orgao AS SELECT codigo_do_imovel, centro_de_custos, sum(total) total FROM opengeo.financeiro WHERE EXTRACT(year FROM competencia) >= EXTRACT(year FROM now()) GROUP BY codigo_do_imovel, centro_de_custos ORDER BY total DESC LIMIT 1000000000
CREATE VIEW lp_predio_custos_tipo AS SELECT codigo_do_imovel, tipo_de_custo, sum(total) total FROM opengeo.financeiro WHERE EXTRACT(year FROM competencia) >= EXTRACT(year FROM now()) GROUP BY codigo_do_imovel, tipo_de_custo ORDER BY total DESC LIMIT 10000000
CREATE VIEW lp_predio_outros_orgaos AS SELECT predio.codigo_do_imovel cod_imovel, orgao.ORGI_CDORGAO, orgao.ORGI_NM_ORGAO, 'ORG' destino FROM exadata.orgi_orgao orgao INNER JOIN (SELECT codigo_do_imovel, codigo_cc FROM opengeo.financeiro GROUP BY codigo_do_imovel, codigo_cc) predio ON predio.codigo_cc = CAST(orgao.ORGI_DK AS STRING) WHERE orgi_tpor_dk NOT IN (1, 3, 5) AND ((orgi_dt_fim IS NULL) OR orgi_dt_fim >= now()) ORDER BY orgao.orgi_nm_orgao ASC LIMIT 100000000
CREATE VIEW lp_predio_procuradorias AS SELECT predio.codigo_do_imovel cod_imovel, orgao.ORGI_CDORGAO, orgao.ORGI_NM_ORGAO, 'PRC' destino FROM exadata.orgi_orgao orgao INNER JOIN (SELECT codigo_do_imovel, codigo_cc FROM opengeo.financeiro GROUP BY codigo_do_imovel, codigo_cc) predio ON predio.codigo_cc = CAST(orgao.ORGI_DK AS STRING) WHERE orgi_tpor_dk = 3 AND ((orgi_dt_fim IS NULL) OR orgi_dt_fim >= now()) ORDER BY orgao.orgi_nm_orgao ASC LIMIT 10000
CREATE VIEW lp_predio_promotorias AS SELECT predio.codigo_do_imovel cod_imovel, orgao.ORGI_CDORGAO, orgao.ORGI_NM_ORGAO, 'PRO' destino FROM exadata.orgi_orgao orgao INNER JOIN (SELECT codigo_do_imovel, codigo_cc FROM opengeo.financeiro GROUP BY codigo_do_imovel, codigo_cc) predio ON predio.codigo_cc = CAST(orgao.ORGI_DK AS STRING) WHERE orgi_tpor_dk = 1 AND ((orgi_dt_fim IS NULL) OR orgi_dt_fim >= now()) ORDER BY orgao.orgi_nm_orgao ASC LIMIT 100000000
CREATE VIEW lp_prefeitos AS SELECT CAST(cod_municipio AS STRING) cod_municipio, cod_craai, governantes.nome, concat(CAST(ano_eleicao AS STRING), '@', '<a href="', url_tse, '" target="blank">Perfil no Tribunal Superior Eleitoral</a>@', 'Site: <a href="http://', trim(site), '" target="blank">', site, '</a>@', 'Telefones: ', telefone, '@', 'Endereço: ', endereco) detalhes, governantes.base64_foto foto, municipio FROM opengeo.lupa_prefeituras prefeituras INNER JOIN opengeo.lupa_governantes_rj governantes ON governantes.cod_ibge = prefeituras.cod_municipio
CREATE VIEW lp_procuradores AS SELECT DISTINCT mmpc_cdorgao, mmpc_nome, concat(mmpc_cargo, '@', 'Concurso: ', mmpc_concurso_romano, ' ano ', CAST(CAST(mmpc_anoconcurso AS INT) AS STRING), '@', 'Nascimento: ', mmpc_dtnasc, '@', 'Atribuição: ', isnull(mmpc_pgj, '--')) detalhes, base64_vtfu_foto foto FROM exadata.mmps_adm_rh_mov_proc INNER JOIN exadata.mmps_vw_rh_foto_func vw_foto ON mmps_adm_rh_mov_proc.mmpc_matricula = vw_foto.vtfu_cdmatricula
CREATE VIEW lp_procuradores_sexo AS SELECT 33 as uf, lp_movimentacao_rh.codigo_municipio as cod_mun,count(DISTINCT lp_movimentacao_rh.cdmatricula) as quant_membros,lp_movimentacao_rh.nmcargo, lp_movimentacao_rh.sexoFROM lupa.lp_movimentacao_rhWHERE lp_movimentacao_rh.cdcargo = 70GROUP BY lp_movimentacao_rh.codigo_municipio, lp_movimentacao_rh.nmcargo, lp_movimentacao_rh.sexo
CREATE VIEW lp_promotores AS SELECT DISTINCT mmpm_cdorgao, mmpm_nome, concat(mmpm_cargo, '@', 'Concurso: ', mmpm_romano, ' ano ', CAST(CAST(mmpm_anoconcurso AS INT) AS STRING), '@', 'Nascimento: ', mmpm_dtnasc, '@', 'Atribuição: ', isnull(mmpm_pgj_funcao, '--')) detalhes, base64_vtfu_foto foto FROM exadata.mmps_adm_rh_mov_prom INNER JOIN exadata.mmps_vw_rh_foto_func vw_foto ON mmps_adm_rh_mov_prom.mmpm_matricula = vw_foto.vtfu_cdmatricula
CREATE VIEW lp_promotores_sexo AS SELECT 33 as uf, lp_movimentacao_rh.codigo_municipio as cod_mun,count(DISTINCT lp_movimentacao_rh.cdmatricula) as quant_membros,lp_movimentacao_rh.nmcargo, lp_movimentacao_rh.sexoFROM lupa.lp_movimentacao_rhWHERE lp_movimentacao_rh.cdcargo = 74GROUP BY lp_movimentacao_rh.codigo_municipio, lp_movimentacao_rh.nmcargo, lp_movimentacao_rh.sexo
CREATE VIEW lp_servidores AS SELECT lotacao.cdorgao_lot_atual cdorgao, lotacao.nome mmsv_nome, concat(lotacao.dstipfunc, '@', 'Nascimento: ', mmsv_dtnasc, '@', 'Função: ', lotacao.cargo_ou_cc_ou_funcao, '@', 'Custo Total MPRJ: R$ ', CAST(CAST(col_k_custo_total_mprj AS DECIMAL(9,2)) AS STRING)) detalhes, base64_vtfu_foto foto FROM exadata.rh_vw_relat_custos_mp_mapas lotacao INNER JOIN exadata.mmps_adm_rh_mov_serv servidor ON servidor.mmsv_matricula = lotacao.cdmatricula INNER JOIN exadata.mmps_vw_rh_foto_func vw_foto ON servidor.mmsv_matricula = vw_foto.vtfu_cdmatricula
CREATE VIEW lp_servidores_estagiarios_mp AS SELECT 33 as uf, lp_movimentacao_rh.codigo_municipio as cod_mun,count(DISTINCT lp_movimentacao_rh.cdmatricula) as quant,lp_movimentacao_rh.nmcargo as cargoFROM lupa.lp_movimentacao_rhWHERE lp_movimentacao_rh.cdcargo NOT IN (70, 74)GROUP BY lp_movimentacao_rh.codigo_municipio, lp_movimentacao_rh.nmcargo
CREATE VIEW lp_servidores_outros AS SELECT 33 as uf, lp_movimentacao_rh.codigo_municipio as cod_mun,count(DISTINCT lp_movimentacao_rh.cdmatricula) as quant_servidoresFROM lupa.lp_movimentacao_rhWHERE lp_movimentacao_rh.cdcargo NOT IN (70, 74)GROUP BY lp_movimentacao_rh.codigo_municipio
CREATE VIEW vw_orgao_codcraai AS SELECT idcraai cod_craai, nm_orgao, orgi_dk FROM lupa.entidade_craai INNER JOIN exadata.orgi_orgao ON orgi_nm_orgao = entidade_craai.nm_orgao
